### ISSUE TITLE
Pug templates need better filter support

### ISSUE THREAD

**Issue by kaceo** [11ty/eleventy-plugin-template-languages#1]
**Is your feature request related to a problem? Please describe.**
One of the best feature of Eleventy is the ability to mix and match different template languages to produce a static site.  This advantage falls short when some template languages are more empowered than others.

Currently Pug does not support Eleventy universal filters.  This makes it difficult for Pug users to adapt to the Eleventy environment, or for a template in one language to be modified into a different language.

**Describe the solution you'd like**
In njk/liquid/md a data is evaluated like this: {{ myData | myFilter }}

In Pug a data is used like this: #{ myData }.  It does not understand this expression #{ myData | myFilter } as only one variable name should be inside the parenthesis.

My solution is for Eleventy to run one pre-processing step in front of the Pug processing.  

During this pre-processing step, Eleventy searches for these expressions #{ *** } and check if they need evaluation (whether there is a | inside the string):

- if there is no filter, just skip this variable.  It will be Pug's responsibility to perform substitution during run.

- if there is a filter expression, Eleventy evaluates the filter and generate a temporary unique variable, and place the variable/value into the data stack, and replace the Pug template variable name.

As Eleventy is a compiler, data values can be determined without side effects during template evaluation.  So the invention of temporary variables to store the evaluated eexpressions is safe.

**Describe alternatives you've considered**
[Similar requests](https://github.com/11ty/eleventy/issues/154) but that suggests a solution that requires extending Pug with user-customisation.  In my opinion, that is a strategy that will lead to incompatibility between Pug and other template languages.

**Additional context**
I come into Eleventy because it is described as a "Jekyll in Nodejs".  I tried to convert a complete site from Jekyll into Eleventy.  Filters are the most problematic issues, as not all Jekyll filters have equivalent (eg. absolute_url, relative_url etc).  But this is solveable by plugins.

Pug as my preferred template language further complicate the development, as it has only some of the expressive power of the other languages.  Although I can rewrite the logic, I want to keep the Eleventy idioms as much as possible, and that means filters should be retained inside Pug.

**Comment by Cyberlane** [comment]
I just wanted to add that this is what currently works for me:

```
  global.filters = eleventyConfig.javascript.filters;
  global.shortcodes = eleventyConfig.javascript.shortcodes;
  eleventyConfig.addPlugin(pugPlugin, {
    globals: ['filters', 'shortcodes'],
  });
```

**Comment by bever1337** [comment]
In v3, I think the suggestion is:
```js
import pugPlugin from "@11ty/eleventy-plugin-pug";

eleventyConfig.addPlugin(pugPlugin, {
  debug: true,
  filters: eleventyConfig.getFilters(),
});
```

But it's giving me some grief. I believe that getFilters somehow loses its `this`, causing typeerrors in places like `getLocaleCollectionItem`.

This project is not using the i18n plugin

```
[11ty] Original error stack trace: TypeError: ./vault/_layouts/bicycle.pug:21
[11ty]     19|     !{content}
[11ty]     20| block footer
[11ty]   > 21|   nav
[11ty]     22|     ul
[11ty]     23|       - console.debug('---\nCOLLECTIONS:',collections,'\nPAGE:', page,'\nARGUMENTS:', arguments, '\n---');
[11ty]     24|       - const previous = filters.getPreviousCollectionItem(collections.bicycles, page);

[11ty] Cannot read properties of undefined (reading 'lang')
[11ty]     at Object.getLocaleCollectionItem (file:///BLAHBLAH/node_modules/@11ty/eleventy/src/Filters/GetLocaleCollectionItem.js:17:17)
[11ty]     at Object.<anonymous> (file:///BLAHBLAH/node_modules/@11ty/eleventy/src/defaultConfig.js:113:34)
[11ty]     at Object.fn [as getPreviousCollectionItem] (file:///BLAHBLAHnode_modules/@11ty/eleventy/src/Benchmark/BenchmarkGroup.js:37:23)
[11ty]     at eval (eval at wrap (/BLAHBLAH/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:66:26)
[11ty]     at template (eval at wrap (/BLAHBLAH/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:97:7)
[11ty]     at exports.render (/BLAHBLAH/node_modules/pug/lib/index.js:423:43)
[11ty]     at Object.<anonymous> (file:///BLAHBLAH/node_modules/@11ty/eleventy-plugin-pug/extension.js:70:15)
[11ty]     at TemplateLayout.renderPageEntry (file:///BLAHBLAH/node_modules/@11ty/eleventy/src/TemplateLayout.js:224:28)
[11ty]     at async #renderPageEntryWithLayoutsAndTransforms (file:///BLAHBLAH/node_modules/@11ty/eleventy/src/Template.js:928:14)
[11ty]     at async Template.generateMapEntry (file:///BLAHBLAH/node_modules/@11ty/eleventy/src/Template.js:967:15)
```

Error is here: https://github.com/11ty/eleventy/blob/f65c10f0cfb6b881613289b6644ae96a55294ebe/src/Filters/GetLocaleCollectionItem.js#L17

`this.page` is undefined, which the filter does not expect.
