### ISSUE TITLE
page object is not available in the JavaScript front matter

### ISSUE THREAD

**Issue by hidegh** [11ty/eleventy-plugin-template-languages#22]
**Describe the bug**
Was experimenting with the possibility to use JS in the front matter (to call some globally defined function. While using the computedData with plain (yaml) front matter, the page.url was working, the same did not worked with JS frontmatter.

Might relate to:
- wrong this binding
- possibly a missing extra parent object under the page is accessible in JS - if so, then also **missing documentation**: https://www.11ty.dev/docs/data-frontmatter/#javascript-front-matter

**Also note:**

**JS front matter** seems to be a powerful tool, adding documentation on how to create and nicely inject JS functions (to be able to call them in the JS font-matter) would be welcome.

Currently I just created a plain ```main = function(p) {  return p; }``` inside the main ```.eleventy.js``` - probably to limit pollution I'd rather add a ```fnc = require('my-functions')``` to import multiple functions safely. This might not be the ideal solution, just the one I was figuring out while playing around.

---

**So details on the described BUG:**

```yaml
---
layout: default
permalink: test/
eleventyComputed:
    title: 'url = {{ page.url }}'
---

```

```js
---js
{   
    layout: "default",
    permalink: 'test/',
    data: main('1..2..3'),
    eleventyComputed: {
        title: `url = ${ page.url }`
    } 
}
---
```

Failed with error:
```
`SyntaxError` was thrown:
    SyntaxError: ReferenceError: page is not defined
        at Object.parse (C:\Users\Balazs\AppData\Roaming\npm\node_modules\@11ty\eleventy\node_modules\gray-matter\lib\engines.js:48:13)
        at module.exports (C:\Users\Balazs\AppData\Roaming\npm\node_modules\@11ty\eleventy\node_modules\gray-matter\lib\parse.js:12:17)
        at parseMatter (C:\Users\Balazs\AppData\Roaming\npm\node_modules\@11ty\eleventy\node_modules\gray-matter\index.js:109:17)
        at matter (C:\Users\Balazs\AppData\Roaming\npm\node_modules\@11ty\eleventy\node_modules\gray-matter\index.js:50:10)
        at Template.read (C:\Users\Balazs\AppData\Roaming\npm\node_modules\@11ty\eleventy\src\TemplateContent.js:82:16)
        at async Template.getFrontMatterData (C:\Users\Balazs\AppData\Roaming\npm\node_modules\@11ty\eleventy\src\TemplateContent.js:141:7)
        at async Template.getData (C:\Users\Balazs\AppData\Roaming\npm\node_modules\@11ty\eleventy\src\Template.js:235:29)
        at async Template.getTemplateMapEntries (C:\Users\Balazs\AppData\Roaming\npm\node_modules\@11ty\eleventy\src\Template.js:744:16)
        at async TemplateMap.add (C:\Users\Balazs\AppData\Roaming\npm\node_modules\@11ty\eleventy\src\TemplateMap.js:32:21)
        at async Promise.all (index 4)
```

**To Reproduce**
Create any **test.njk**, use the 2 provided front matters to test (actually remove the data: main('1..2..3') from the JS).

With JS frontmatter the exception with the stack-trace above will occur.

**Expected behavior**
When processing JS front-matter and using **computedData** same objects should be avail. as in case of YAML.

**Screenshots**
n/a

**Environment:**

- OS and Version: Win 10
- Eleventy Version: 0.11.1

**Additional context**
n/a

**Comment by zachleat** [comment]
fwiw I’d prefer we start recommending folks use arbitrary JavaScript in front matter (available in v3 and newer) rather than the JavaScript object syntax. I think it’s just more familiar for folks: https://www.11ty.dev/docs/data-frontmatter/#java-script-front-matter

I’d also pass a nod to https://www.11ty.dev/docs/permalinks/#disable-templating-in-permalinks here for folks visiting later
