### ISSUE TITLE
Parse error on some handlebars code snippets in markdown

### ISSUE THREAD

**Issue by mehulkar** [11ty/eleventy-plugin-template-languages#9]
**Describe the bug**
Exception in markdown template parsing:

```
 ```hbs
<h1>{{or @foo "default"}}</h1>
\```
```

I've included a backslash in the snippet below for Github's markdown parsing, it is not in my actual markdown file

**To Reproduce**

1. With `"@11ty/eleventy": "1.0.0"`
2. Create `.md` file with syntax above
3. `npm run start` or `npm run build`

    ```
    [11ty] > Having trouble rendering liquid template ./source/my-file.md

    `TemplateContentRenderError` was thrown
    [11ty] > unexpected token at "@foo \"default\"", file:./source/my-file.md, line:237, col:5

    `ParseError` was thrown
    [11ty] > unexpected token at "@foo \"default\""

    `AssertionError` was thrown:
    [11ty]     AssertionError: unexpected token at "@foo \"default\""
            at new AssertionError (/dev/project/node_modules/liquidjs/dist/liquid.node.cjs.js:664:28)
            at assert (/dev/project/node_modules/liquidjs/dist/liquid.node.cjs.js:822:15)
            at Tokenizer.readFilter (/dev/project/node_modules/liquidjs/dist/liquid.node.cjs.js:1944:9)
            at Tokenizer.readFilters (/dev/project/node_modules/liquidjs/dist/liquid.node.cjs.js:1933:31)
            at new Value (/dev/project/node_modules/liquidjs/dist/liquid.node.cjs.js:2418:34)
            at new Output (/dev/project/node_modules/liquidjs/dist/liquid.node.cjs.js:2501:23)
            at Parser.parseToken (/dev/project/node_modules/liquidjs/dist/liquid.node.cjs.js:2562:24)
            at Parser.parseTokens (/dev/project/node_modules/liquidjs/dist/liquid.node.cjs.js:2552:33)
            at Parser.parse (/dev/project/node_modules/liquidjs/dist/liquid.node.cjs.js:2546:21)
            at Liquid.parse (/dev/project/node_modules/liquidjs/dist/liquid.node.cjs.js:4280:28)
    [11ty] Wrote 0 files in 0.33 seconds (v1.0.0)
    ```    

**Environment:**

- OS and Version: macOS Montererry
- Eleventy Version: 1.0.0

**Additional context**

Build worked fine with `v0.12.1`!

**Comment by jrgtt** [comment]
Thanks @pdehaan wrapping my handlebars content with `{% raw %} ... {% endraw %}` works!
